### ISSUE TITLE
Dead-zone value limited to 255 when it can be higher.

### ISSUE THREAD

**Issue by Yoshisaur310** [jdanders/JoyConCal#1]
This has been a great program for one of my joy cons which doesn't seem to save dead zone values with the only other program I have found that can edit dead zones on Joy Cons (Joy-Con Toolkit).

However, I noticed that your program seems to be capped at 255 (equivalent to FF in Joy-Con Toolkit) instead of 4095 (equivalent to FFF in Joy-Con Toolkit). After looking through the source code (JoyConCal.cpp), it seems this is because u8 is used to calculate the dead-zones. My Joy Con is very peculiar in that it drifts inconsistently, requiring a higher value to avoid off center movement. This makes it difficult for this program to accurately decide my dead-zone without multiple attempts or just editing the JoyConCal.cpp file to specify my intended value and building the program.

Having an option to decide how much dead-zone you want could be very helpful as well as being able to use values higher than 255. How feasible are these two suggestions to implement at this moment?

**Comment by jdanders** [comment]
Sorry, I don't even own any Joy Cons any more. If you'd like to submit a pull request, I'll merge it, but I don't have any way to test.
